jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400000



spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/data/testdb
      # 또는 jdbc:h2:tcp://localhost:9092/./data/testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      springframework:
        security: DEBUG
