version: '3'

services:
  test_database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
    - 3306:3306

  spring-boot:
    image: spring-mysql
    ports:
    - 8080:8080
    depends_on:
      - test_database